### ISSUE TITLE
limit of pages  for conversion

### ISSUE THREAD

**Issue by ehtisham-Fazal** [ArtifexSoftware/pdf2docx#247]
i m converting more than  15 pages  and its generating fonts issue but when i am running for  same file less than 15 pages its working anyone plz guide me, may be i am missing something . Thanks

**Comment by Hamza-nabil** [comment]
I think that the problem is likely on a page beyond the initial 15. could you please provide the complete error message ?

**Comment by ehtisham-Fazal** [comment]
cv.convert(path_output,pages=[0,1,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
i am using this and it working and then i add 
cv.convert(path_output,pages=[0,1,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ])
and then getting this error in __init__
    _fitz.Font_swiginit(self, _fitz.new_Font(fontname, fontfile, fontbuffer, script, language, ordering, is_bold, is_italic, is_serif, embed))
    so i have just changed page number 14 with 15 and put it for only 15 pages except page number 14 it's working but when i am adding more than 15 pages getting same error

**Comment by ehtisham-Fazal** [comment]
can we change input file fonts if its not present in pre defined fonts

**Comment by Hamza-nabil** [comment]
I think that you can change the default fount , see #216

**Comment by dothinking** [comment]
@ehtisham-Fazal thanks for reporting this issue.

could you please copy paste the full error message? and what's your pdf2docx version?

**Comment by ehtisham-Fazal** [comment]
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
Traceback (most recent call last):
  File "c:/Users/Desktop/test.py", line 10, in <module>
    cv_obj.convert(docx_file)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\converter.py", line 352, in convert
    self.parse(start, end, pages, **settings).make_docx(docx_filename, **settings)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\converter.py", line 126, in parse
    return self.load_pages(start, end, pages) \
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\converter.py", line 167, in parse_document
    self._pages.parse(self.fitz_doc, **kwargs)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\page\Pages.py", line 37, in parse
    raw_page.restore(**settings)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\common\share.py", line 226, in inner
    objects = func(*args, **kwargs)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\page\RawPage.py", line 67, in restore
    super().restore(raw_dict)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\layout\Layout.py", line 74, in restore
    self.blocks.restore(data.get('blocks', []))
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\layout\Blocks.py", line 98, in restore
    block = TextBlock(raw_block)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\TextBlock.py", line 49, in __init__
    self.lines = Lines(parent=self).restore(raw.get('lines', []))
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\Lines.py", line 31, in restore
    line = Line(raw)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\Line.py", line 54, in __init__
    self.spans = Spans(parent=self).restore(raw.get('spans', []))
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\Spans.py", line 19, in restore
    span = TextSpan(raw_span)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\TextSpan.py", line 78, in __init__
    self._change_font_and_update_bbox(constants.DEFAULT_FONT_NAME)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\pdf2docx\text\TextSpan.py", line 121, in _change_font_and_update_bbox
    font = fitz.Font(font_name)
  File "C:\Users\anaconda3\envs\pdf2docx_env\lib\site-packages\fitz\fitz.py", line 9364, in __init__
    _fitz.Font_swiginit(self, _fitz.new_Font(fontname, fontfile, fontbuffer, script, language, ordering, is_bold, is_italic, is_serif, embed))

**Comment by dothinking** [comment]
I guess your pdf2docx version is `0.5.6` or even lower.

This issue was fixed several days ago. Please refer to the fix as mentioned by @Hamza-nabil . Or just upgrade your pdf2docx.

```
Pio install pdf2docx --upgrade
```

**Comment by ehtisham-Fazal** [comment]
yes my version is 0.5.6
