### ISSUE TITLE
[ERROR] Ignore page 1 due to making page error: invalid literal for int() with base 16: 'x1'

### ISSUE THREAD

**Issue by jangkim7** [ArtifexSoftware/pdf2docx#329]
### Description of the bug

I am unable to convert the attached PDF to DOCX.

[sample.pdf](https://github.com/user-attachments/files/18033880/sample.pdf)

I am using the parse method to simply convert all pages.

parse("sample.pdf", "sample.docx")

Here is the output that I get:

[INFO] Start to convert sample.pdf
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
[INFO] [3/4] Parsing pages...
[INFO] (1/1) Page 1
[INFO] [4/4] Creating pages...
[INFO] (1/1) Page 1
[ERROR] Ignore page 1 due to making page error: invalid literal for int() with base 16: 'x1'
[INFO] Terminated in 0.21s.

### How to reproduce the bug

See my description. It has the sample PDF file and the code snippet causing the error.

### pdf2docx version

0.5.8

### Operating system

MacOS

### Python version

3.10

**Comment by JoshhMiranda** [comment]
I am currently facing the same issue as well. The same code was working fine 10 hours ago but now fails. The error is as follows:
**_[ERROR] Ignore page 1 due to making page error: invalid literal for int() with base 16: 'x1'_**

**Comment by jangkim7** [comment]
I can't get any PDFs to work. I thought it was related to my specific PDF, but that doesn't seem to be the case. Every PDF I try fails.

**Comment by JoshhMiranda** [comment]
It seems to be a issue with the library itself unfortunately.

**Comment by jcgarciaca** [comment]
`pdf2docx` depends on `fonttools` and `PyMuPDF`. They were recently updated. So, I downgraded them (though I’m not sure if the issue was caused by one or both). However, this worked for me.

**Comment by JoshhMiranda** [comment]
Could you specify which version of PuMuPDF and fonttools you're using after downgrading them?

**Comment by JoshhMiranda** [comment]
I tried downgrading PyMuPDF and fonttools to these versions: and pdf2docx works now.
@jcgarciaca thanks for the ideaa!!!
@jangkim7 this will solve your issue.

_pip install PyMuPDF==1.24.14
pip install fonttools==4.55.0_

**Comment by jangkim7** [comment]
Thank you, this worked!

**Comment by HelpFireCode** [comment]
Thank you！ this worked！

**Comment by piscesvivian** [comment]
It seems to a 100% chance happens error.

**Comment by hstov3** [comment]
Thanks much for the workaround [above](https://github.com/ArtifexSoftware/pdf2docx/issues/329#issuecomment-2524855908).  

During debugging, the stack trace of the captured exception is: 

```
Traceback (most recent call last):
  File "<env_dir>\lib\site-packages\pdf2docx\converter.py", line 225, in make_docx
    page.make_docx(docx_file)
  File "<env_dir>\lib\site-packages\pdf2docx\page\Page.py", line 202, in make_docx
    self.sections.make_docx(doc)
  File "<env_dir>\lib\site-packages\pdf2docx\layout\Sections.py", line 55, in make_docx
    section.make_docx(doc)
  File "<env_dir>\lib\site-packages\pdf2docx\layout\Section.py", line 97, in make_docx
    column.make_docx(doc)
  File "<env_dir>\lib\site-packages\pdf2docx\layout\Column.py", line 49, in make_docx
    self.blocks.make_docx(doc)
  File "<env_dir>\lib\site-packages\pdf2docx\layout\Blocks.py", line 327, in make_docx
    block.make_docx(p)
  File "<env_dir>\lib\site-packages\pdf2docx\text\TextBlock.py", line 366, in make_docx
    for line in self.lines: line.make_docx(p)
  File "<env_dir>\lib\site-packages\pdf2docx\text\Line.py", line 175, in make_docx
    for span in self.spans: span.make_docx(p)
  File "<env_dir>\lib\site-packages\pdf2docx\text\TextSpan.py", line 379, in make_docx
    self._set_text_format(docx_run)
  File "<env_dir>\lib\site-packages\pdf2docx\text\TextSpan.py", line 406, in _set_text_format
    docx_run.font.color.rgb = RGBColor(*rgb_component(self.color))
  File "<env_dir>\lib\site-packages\pdf2docx\common\share.py", line 162, in rgb_component
    return [int(s[i:i+2], 16) for i in [0, 2, 4]]
  File "<env_dir>\lib\site-packages\pdf2docx\common\share.py", line 162, in <listcomp>
    return [int(s[i:i+2], 16) for i in [0, 2, 4]]
ValueError: invalid literal for int() with base 16: 'x1'
```

`self.color` at line 406  in TextSpan.py is: `-16777216`
the negative value breaks `rgb_component()`
